<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Organization extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'partner_id',
        'name',
        'code',
        'legal_name',
        'type',
        'status',
        'email',
        'phone',
        'website',
        'street',
        'street2',
        'city',
        'state',
        'zip',
        'country',
        'separate_billing_address',
        'billing_street',
        'billing_city',
        'billing_state',
        'billing_zip',
        'billing_country',
        'tax_id',
        'vat_number',
        'company_registry',
        'industry',
        'plan',
        'billing_cycle',
        'trial_ends_at',
        'subscription_ends_at',
        'payment_method',
        'stripe_customer_id',
        'max_users',
        'storage_limit_bytes',
        'storage_used_bytes',
        'timezone',
        'locale',
        'currency',
        'date_format',
        'fiscal_year_start',
        'logo_path',
        'enabled_modules',
        'notes',
        'metadata',
    ];

    protected $casts = [
        'separate_billing_address' => 'boolean',
        'trial_ends_at' => 'date',
        'subscription_ends_at' => 'date',
        'max_users' => 'integer',
        'storage_limit_bytes' => 'integer',
        'storage_used_bytes' => 'integer',
        'enabled_modules' => 'array',
        'metadata' => 'array',
    ];

    protected $attributes = [
        'type' => 'company',
        'status' => 'trial',
        'plan' => 'free',
        'billing_cycle' => 'monthly',
        'max_users' => 3,
        'storage_limit_bytes' => 5368709120, // 5GB
        'timezone' => 'UTC',
        'locale' => 'en',
        'currency' => 'USD',
        'date_format' => 'Y-m-d',
        'fiscal_year_start' => '01-01',
        'country' => 'US',
    ];

    // Organization types
    const TYPE_COMPANY = 'company';
    const TYPE_NONPROFIT = 'nonprofit';
    const TYPE_GOVERNMENT = 'government';
    const TYPE_EDUCATION = 'education';
    const TYPE_INDIVIDUAL = 'individual';

    // Status values
    const STATUS_TRIAL = 'trial';
    const STATUS_ACTIVE = 'active';
    const STATUS_SUSPENDED = 'suspended';
    const STATUS_CANCELLED = 'cancelled';

    // Plans
    const PLAN_FREE = 'free';
    const PLAN_STARTER = 'starter';
    const PLAN_PROFESSIONAL = 'professional';
    const PLAN_ENTERPRISE = 'enterprise';

    /**
     * Partner managing this organization
     */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Partner::class);
    }

    /**
     * Users belonging to this organization
     */
    public function users(): HasMany
    {
        return $this->hasMany(User::class);
    }

    /**
     * Modules enabled for this organization
     */
    public function modules(): HasMany
    {
        return $this->hasMany(OrganizationModule::class);
    }

    /**
     * Invitations for this organization
     */
    public function invitations(): HasMany
    {
        return $this->hasMany(OrganizationInvitation::class);
    }

    /**
     * Revenue generated by this organization (for partner)
     */
    public function partnerRevenue(): HasMany
    {
        return $this->hasMany(PartnerRevenue::class);
    }

    /**
     * Generate a unique organization code
     */
    public static function generateCode(): string
    {
        do {
            $code = 'ORG-' . strtoupper(substr(md5(uniqid()), 0, 8));
        } while (static::where('code', $code)->exists());

        return $code;
    }

    /**
     * Check if organization is in trial
     */
    public function isInTrial(): bool
    {
        return $this->status === self::STATUS_TRIAL 
            && $this->trial_ends_at 
            && $this->trial_ends_at->isFuture();
    }

    /**
     * Check if trial has expired
     */
    public function isTrialExpired(): bool
    {
        return $this->status === self::STATUS_TRIAL 
            && $this->trial_ends_at 
            && $this->trial_ends_at->isPast();
    }

    /**
     * Check if organization is active (trial or paid)
     */
    public function isActive(): bool
    {
        if ($this->status === self::STATUS_ACTIVE) {
            return true;
        }

        return $this->isInTrial();
    }

    /**
     * Get days remaining in trial
     */
    public function getTrialDaysRemainingAttribute(): ?int
    {
        if (!$this->trial_ends_at) {
            return null;
        }

        return max(0, now()->diffInDays($this->trial_ends_at, false));
    }

    /**
     * Check if organization can add more users
     */
    public function canAddUser(): bool
    {
        return $this->users()->count() < $this->max_users;
    }

    /**
     * Get storage usage percentage
     */
    public function getStorageUsagePercentAttribute(): float
    {
        if ($this->storage_limit_bytes === 0) {
            return 0;
        }

        return round(($this->storage_used_bytes / $this->storage_limit_bytes) * 100, 2);
    }

    /**
     * Get storage used in human readable format
     */
    public function getStorageUsedHumanAttribute(): string
    {
        return $this->formatBytes($this->storage_used_bytes);
    }

    /**
     * Get storage limit in human readable format
     */
    public function getStorageLimitHumanAttribute(): string
    {
        return $this->formatBytes($this->storage_limit_bytes);
    }

    /**
     * Format bytes to human readable
     */
    protected function formatBytes(int $bytes): string
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];
        $i = 0;
        while ($bytes >= 1024 && $i < count($units) - 1) {
            $bytes /= 1024;
            $i++;
        }
        return round($bytes, 2) . ' ' . $units[$i];
    }

    /**
     * Check if a module is enabled
     */
    public function hasModule(string $moduleId): bool
    {
        return $this->modules()
            ->where('module_id', $moduleId)
            ->where('is_active', true)
            ->exists();
    }

    /**
     * Enable a module
     */
    public function enableModule(string $moduleId, array $options = []): OrganizationModule
    {
        return $this->modules()->updateOrCreate(
            ['module_id' => $moduleId],
            [
                'is_active' => true,
                'activated_at' => now(),
                'monthly_price' => $options['monthly_price'] ?? 0,
                'yearly_price' => $options['yearly_price'] ?? 0,
                'settings' => $options['settings'] ?? null,
            ]
        );
    }

    /**
     * Disable a module
     */
    public function disableModule(string $moduleId): bool
    {
        return $this->modules()
            ->where('module_id', $moduleId)
            ->update(['is_active' => false]);
    }

    /**
     * Get active modules
     */
    public function getActiveModulesAttribute(): array
    {
        return $this->modules()
            ->where('is_active', true)
            ->pluck('module_id')
            ->toArray();
    }

    /**
     * Calculate monthly subscription cost
     */
    public function getMonthlySubscriptionCostAttribute(): float
    {
        return $this->modules()
            ->where('is_active', true)
            ->sum('monthly_price');
    }

    /**
     * Calculate yearly subscription cost
     */
    public function getYearlySubscriptionCostAttribute(): float
    {
        return $this->modules()
            ->where('is_active', true)
            ->sum('yearly_price');
    }

    /**
     * Get owner user
     */
    public function getOwnerAttribute(): ?User
    {
        return $this->users()->where('role', 'owner')->first();
    }

    /**
     * Scope for active organizations
     */
    public function scopeActive($query)
    {
        return $query->whereIn('status', [self::STATUS_TRIAL, self::STATUS_ACTIVE]);
    }

    /**
     * Scope for a specific partner
     */
    public function scopeForPartner($query, $partnerId)
    {
        return $query->where('partner_id', $partnerId);
    }

    /**
     * Get full address
     */
    public function getFullAddressAttribute(): string
    {
        $parts = array_filter([
            $this->street,
            $this->street2,
            $this->city,
            $this->state,
            $this->zip,
            $this->country,
        ]);

        return implode(', ', $parts);
    }

    /**
     * Get billing address
     */
    public function getBillingAddressAttribute(): string
    {
        if (!$this->separate_billing_address) {
            return $this->full_address;
        }

        $parts = array_filter([
            $this->billing_street,
            $this->billing_city,
            $this->billing_state,
            $this->billing_zip,
            $this->billing_country,
        ]);

        return implode(', ', $parts);
    }
}
